spring:
  datasource:
    url: jdbc:sqlserver://adilkhan.database.windows.net:1433;database=Adildb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adilkhan
    password: khan@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


